# Generated by Django 4.2.3 on 2023-08-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Nombre')),
                ('sipnosis', models.TextField()),
                ('pub', models.DateField()),
                ('image', models.ImageField(upload_to=None)),
                ('author', models.ManyToManyField(to='author.author', verbose_name='Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Book',
                'managed': True,
            },
        ),
    ]
