# Generated by Django 4.2.3 on 2023-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=15, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('web_site', models.CharField(max_length=150, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Editorial',
                'managed': True,
            },
        ),
    ]
