# Generated by Django 4.2.3 on 2023-08-05 03:42

import applications.binnacle.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinnacleProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
            options={
                'verbose_name': 'BinnacleProgres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinnacleQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(default=0, validators=[applications.binnacle.validators.validate_value], verbose_name='Contenido')),
                ('writing', models.IntegerField(default=0, validators=[applications.binnacle.validators.validate_value], verbose_name='Escritura')),
                ('dising', models.IntegerField(default=0, validators=[applications.binnacle.validators.validate_value], verbose_name='Diseño')),
            ],
            options={
                'verbose_name': 'BinnacleQualification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinnacleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'BinnacleState',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('phrase', models.TextField(verbose_name='Frases')),
                ('commet', models.TextField(verbose_name='Comentarios')),
                ('buy', models.DateField(verbose_name='Fecha de compra')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Author')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Libro')),
                ('progres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binnacle.binnacleprogres', verbose_name='Progreso')),
                ('qualification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binnacle.binnaclequalification', verbose_name='Calificacion')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binnacle.binnaclestate', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Binnacle',
                'managed': True,
            },
        ),
    ]
